name = "youtunes-lol"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Cloudflare R2 binding for music storage
[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "youtunes-music"

# Custom domain configuration
# Domain: youtunes.lol will be configured via Cloudflare dashboard

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "youtunes-music"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.preview.r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "youtunes-music-preview"
