name = "youtunes-lol"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

# Custom domain configuration
# After deploying, add custom domain in Cloudflare dashboard:
# Pages > youtunes-lol > Custom domains > Add youtunes.lol

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }
